### ISSUE TITLE
start eaf-rss-reader failed due to index.html not found

### ISSUE THREAD

**Issue by lennonwoo** [emacs-eaf/eaf-rss-reader#1]
Hi I'd like to use eaf-rss-reader, but after I M-x run `eaf-open-rss-reader`, it started failed.

After checking the log on `*eaf*` buffer, I found that it is due to index.html not found.

The detail log as below.
```
Traceback (most recent call last):
  File "/Users/zhenye.wu/Dropbox/dotfiles/.emacs.d/elisp/extensions/emacs-application-framework/core/utils.py", line 60, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/Users/zhenye.wu/.emacs.d/elisp/extensions/emacs-application-framework/eaf.py", line 170, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/Users/zhenye.wu/.emacs.d/elisp/extensions/emacs-application-framework/eaf.py", line 187, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
  File "/Users/zhenye.wu/.emacs.d/elisp/extensions/eaf-rss-reader/buffer.py", line 47, in __init__
    self.load_index_html(__file__)
  File "/Users/zhenye.wu/Dropbox/dotfiles/.emacs.d/elisp/extensions/emacs-application-framework/core/webengine.py", line 1378, in load_index_html
    with open(self.index_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/zhenye.wu/.emacs.d/elisp/extensions/eaf-rss-reader/dist/index.html'
```

Do I need run some commands to convert Vue files to index.html first? Or any other steps I missed out?

Thanks!

**Comment by manateelazycat** [comment]
You need run ./install-eaf.py after upgrade EAF.
